# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4369df3cd0d031b9a74f804560cfcbfbd78fec1127dc9383bb9f43138b803e7e47c4b1107ead8422f3accbc08118edadb007580b2cd73f1ae2ff7d21766c2e77

test:
  secret_key_base: e8c40b0425942aa1a8d6e3e23025244a884c9a4b8c27c43988d053caee26318b4d584537f487c686c1d73fc9e14d1511a45020a52e4bd6cbf7cd0fe0c542ddaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
